# zeroweather.conf
web_server.bind_address=<bind IP address>
web_server.bind_port=8080

sensor_w1.path=/sys/bus/w1/devices/28-00000f9d79d8/w1_slave
sensor_w1.ma_window=10
sensor_w1.threshold=0.3

general.log_path=/home/petste/ZeroWeather/logs/app.log
general.log_level=Warn
general.log_to_stdout=false
